server:
  port: 9005

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nietup/hello_microservice-config-server
          clone-on-start: true