server:
  port: 9004

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
        - id: GRADE-SERVICE
          uri: lb://GRADE-SERVICE
          predicates:
            - Path=/grades/**
    config:
      enabled: false

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9003/eureka

---

spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    preferIpAddress: false
    hostname: "localhost"
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka