server:
  port: 9004

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
        - id: GRADE-SERVICE
          uri: lb://GRADE-SERVICE
          predicates:
            - Path=/grades/**
    config:
      enabled: true
  config:
    import: configserver:http://localhost:9005
