apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service-app
  labels:
        app: grade-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-service-app
  template:
    metadata:
      labels:
        app: grade-service-app
    spec:
      containers:
      - name: grade-service-app
        image: nietup/grade-service:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 9001

---

kind: Service
apiVersion: v1
metadata:
  name:  grade-service-scv
spec:
  selector:
    app:  grade-service-app
  ports:
  - port:  80
    targetPort:  9001
