server:
  port: 9001

spring:
  application:
    name: GRADE-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9003/eureka
  instance:
    hostname: localhost