server:
  port: 9002

spring:
  application:
    name: STUDENT-SERVICE
  cloud:
    config:
      enabled: true
  config:
    import: configserver:http://localhost:9005

resilience4j:
  timelimiter:
    instances:
      student:
        timeoutDuration: 2s
