server:
  port: 9002

spring:
  application:
    name: STUDENT-SERVICE
  cloud:
    config:
      enabled: true
  config:
    import: configserver:http://localhost:9005

resilience4j:
  timelimiter:
    instances:
      student:
        timeoutDuration: 2s

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9003/eureka