server:
  port: 9002

spring:
  application:
    name: STUDENT-SERVICE
  cloud:
    config:
      enabled: false
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    circuitbreaker:
      enabled: false

resilience4j:
  timelimiter:
    instances:
      student:
        timeoutDuration: 2s

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9003/eureka

---

spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    preferIpAddress: false
    hostname: "localhost"
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka
